services:
  redis:
    container_name: redis
    image: redis
    restart: always
    expose:
      - 6379
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - backend

volumes:
  redis-data:

networks:
  backend:
    driver: bridge
