services:
  tg-anime:
    container_name: tg-anime
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ../.env
    ports:
      - "${API_PORT_DOCKER}:8000"
    command: "uvicorn --factory app.api.main:create_app --reload --log-config /app/app/logging.yaml --host 0.0.0.0 --port 8000"
    volumes:
      - ../app/:/app/app
    networks:
      - backend

networks:
  backend:
    driver: bridge
