version: 1

disable_existing_loggers: false

formatters:
  uvicorn.default:
    (): "uvicorn.logging.DefaultFormatter"
    fmt: "%(levelprefix)-8s %(asctime)-23s \t%(name)s \t%(filename)s:%(lineno)s \t%(message)s"
    use_colors: true

  uvicorn.access:
    (): "uvicorn.logging.AccessFormatter"
    fmt: "%(levelprefix)-8s %(asctime)-23s \t%(name)s \t%(client_addr)s - \"%(request_line)s\" %(status_code)s"
    use_colors: true

handlers:
  default:
    class: logging.StreamHandler
    formatter: uvicorn.default
    stream: ext://sys.stdout

  error:
    class: logging.StreamHandler
    formatter: uvicorn.default
    stream: ext://sys.stderr

  uvicorn.access:
    class: logging.StreamHandler
    formatter: uvicorn.access
    stream: ext://sys.stdout

loggers:
  "":
    handlers:
      - default
    level: INFO
    propagate: false

  "uvicorn":
    handlers: ["default"]
    level: INFO
    propagate: false

  "uvicorn.access":
    handlers: ["uvicorn.access"]
    level: INFO
    propagate: false

  "uvicorn.error":
    handlers: ["error"]
    level: INFO
    propagate: false

  "sqlalchemy.engine":
    handlers: ["error"]
    level: WARNING
    propagate: false
